version: '3'
services:
  fastapi-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: bash -c "python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
